language: go

go:
  - master

# Only clone the most recent commit.
git:
  depth: 1

before_install:
  - chmod a+x ./travis/install.sh
  - chmod a+x ./travis/build.sh

install:
  - "./travis/install.sh"
script:
  - "./travis/build.sh"

deploy:
  - provider: releases
    file_glob: true
    file:
      - dist/*
    api_key: $GITHUB_TOKEN
    skip_cleanup: true
    on:
      tags: true


notifications:
  email:
    recipients:
      - hldtux@gmail.com
    on_success: never # default: change
    on_failure: always # default: always